component:
  name: example-component
  version: 1.0.0
  type: service
  build:
    dockerfile: Dockerfile
  deployment:
    replicas: 2
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "250m"
        memory: "256Mi"
